# Deprecated settings #
# preload = ~/Pictures/Wallpapers/mononoke010.jpg
# wallpaper = DP-3,~/Pictures/Wallpapers/mononoke010.jpg
# splash = false
#fully disable ipc
# ipc = off

wallpaper {
    monitor = DP-3
    path = ~/Pictures/Wallpapers/karigurashi001.jpg
    fit_mode = cover
}
